version: '3.8'

services:
  web:
    build: .
    container_name: api8inf349
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=inf349.py
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=api8inf349
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: api8inf349
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:5
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
